/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => TinyChartPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/settings/pluginSettings.ts
var DEFAULT_SETTINGS = {
  fillChar: "\u2588",
  emptyChar: "-",
  zeroPointChar: "|",
  showZeroPoint: true,
  prefixChar: "",
  suffixChar: "",
  chartLength: 20,
  codeBlock: true,
  showLabels: true,
  rightAlignLabels: true
};

// src/settings/settingsTab.ts
var import_obsidian = require("obsidian");
var SettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Fill character").setDesc("Single character (required)").addText(
      (text) => text.setPlaceholder("Enter a character").setValue(this.plugin.settings.fillChar).onChange(async (value) => {
        if (value) {
          if (value.length > 1) {
            value = value.slice(0, 1);
            text.setValue(value);
            new import_obsidian.Notice("Enter only a single character");
          }
          this.plugin.settings.fillChar = value;
          await this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian.Setting(containerEl).setName("Empty character").setDesc("Single character (optional)").addText(
      (text) => text.setPlaceholder("Enter a character").setValue(this.plugin.settings.emptyChar).onChange(async (value) => {
        if (value) {
          if (value.length > 1) {
            value = value.slice(0, 1);
            text.setValue(value);
            new import_obsidian.Notice("Enter only a single character");
          }
          this.plugin.settings.emptyChar = value;
          await this.plugin.saveSettings();
        } else {
          this.plugin.settings.emptyChar = "\u200E";
          await this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian.Setting(containerEl).setName("Prefix character").setDesc("Single character (optional)").addText(
      (text) => text.setPlaceholder("Enter a character").setValue(this.plugin.settings.prefixChar).onChange(async (value) => {
        if (value.length > 1) {
          value = value.slice(0, 1);
          text.setValue(value);
          new import_obsidian.Notice("Enter only a single character");
        }
        this.plugin.settings.prefixChar = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Suffix character").setDesc("Single character (optional)").addText(
      (text) => text.setPlaceholder("Enter a character").setValue(this.plugin.settings.suffixChar).onChange(async (value) => {
        if (value.length > 1) {
          value = value.slice(0, 1);
          text.setValue(value);
          new import_obsidian.Notice("Enter only a single character");
        }
        this.plugin.settings.suffixChar = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Zero point character").setDesc("Character marking the zero point in bidirectional charts").addText(
      (text) => text.setPlaceholder("|").setValue(this.plugin.settings.zeroPointChar).onChange(async (value) => {
        if (value && value.length > 1) {
          value = value.slice(0, 1);
          text.setValue(value);
          new import_obsidian.Notice("Enter only a single character");
        }
        this.plugin.settings.zeroPointChar = value || "|";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Show zero point").setDesc("Display zero point marker in bidirectional charts").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showZeroPoint).onChange(async (value) => {
        this.plugin.settings.showZeroPoint = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Chart length").setDesc("Length of barchart (excluding prefix/suffix and labels)").addSlider(
      (text) => text.setLimits(10, 50, 10).setValue(this.plugin.settings.chartLength).onChange(async (value) => {
        this.plugin.settings.chartLength = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Show labels").setDesc("Display value labels").addToggle(
      (text) => text.setValue(this.plugin.settings.showLabels).onChange(async (value) => {
        this.plugin.settings.showLabels = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Right align labels").setDesc(
      "Align value labels to the right (Recommend disabling if using no empty character)"
    ).addToggle(
      (text) => text.setValue(this.plugin.settings.rightAlignLabels).onChange(async (value) => {
        this.plugin.settings.rightAlignLabels = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Code block (recommended)").setDesc("Render the chart in a codeblock instead of a paragraph").addToggle(
      (text) => text.setValue(this.plugin.settings.codeBlock).onChange(async (value) => {
        this.plugin.settings.codeBlock = value;
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/charts/parseInput.ts
function parseInput(inputString) {
  const data = [];
  const lines = inputString.trim().split("\n");
  for (const line of lines) {
    const [key, value] = line.split(",");
    const trimmedKey = key.trim();
    const trimmedValue = parseInt(value.trim(), 10);
    data.push({ key: trimmedKey, value: trimmedValue });
  }
  return data;
}

// src/charts/horizontalBar.ts
function calculateChartMetrics(data, chartLength) {
  const values = data.map((entry) => entry.value);
  const maxValue = Math.max(...values, 0);
  const minValue = Math.min(...values, 0);
  const range = maxValue - minValue;
  const hasNegative = minValue < 0;
  const hasPositive = maxValue > 0;
  let zeroPos;
  if (minValue >= 0) {
    zeroPos = 0;
  } else if (maxValue <= 0) {
    zeroPos = chartLength;
  } else {
    zeroPos = Math.floor(Math.abs(minValue) / range * chartLength);
  }
  return {
    maxValue,
    minValue,
    range,
    zeroPos,
    hasNegative,
    hasPositive
  };
}
function generateBidirectionalBar(value, metrics, chartLength, fillChar, emptyChar, zeroPointChar, showZeroPoint) {
  const { maxValue, minValue, zeroPos } = metrics;
  if (value === 0) {
    const leftEmpty = emptyChar.repeat(zeroPos);
    const rightEmpty = emptyChar.repeat(chartLength - zeroPos);
    const zeroMark = showZeroPoint ? zeroPointChar : " ";
    return leftEmpty + zeroMark + rightEmpty;
  } else if (value > 0) {
    const rightLength = Math.floor(
      value / maxValue * (chartLength - zeroPos)
    );
    const leftEmpty = emptyChar.repeat(zeroPos);
    const zeroMark = showZeroPoint ? zeroPointChar : " ";
    const rightFill = fillChar.repeat(rightLength);
    const rightEmpty = emptyChar.repeat(chartLength - zeroPos - rightLength);
    return leftEmpty + zeroMark + rightFill + rightEmpty;
  } else {
    const leftLength = Math.floor(
      Math.abs(value) / Math.abs(minValue) * zeroPos
    );
    const leftEmpty = emptyChar.repeat(zeroPos - leftLength);
    const leftFill = fillChar.repeat(leftLength);
    const zeroMark = showZeroPoint ? zeroPointChar : " ";
    const rightEmpty = emptyChar.repeat(chartLength - zeroPos);
    return leftEmpty + leftFill + zeroMark + rightEmpty;
  }
}
function generateBarChart(data, settings) {
  const chartLength = settings.chartLength;
  const fillChar = settings.fillChar;
  const emptyChar = settings.emptyChar;
  const zeroPointChar = settings.zeroPointChar;
  const showZeroPoint = settings.showZeroPoint;
  const showLabelsFlag = settings.showLabels;
  const rightAlignLabelsFlag = settings.rightAlignLabels;
  const prefixChar = settings.prefixChar;
  const suffixChar = settings.suffixChar;
  const metrics = calculateChartMetrics(data, chartLength);
  const maxValueLength = Math.max(
    ...data.map((entry) => {
      const absLength = Math.abs(entry.value).toString().length;
      return entry.value < 0 ? absLength + 1 : absLength;
    })
  );
  const maxKeyLength = Math.max(
    ...data.map((entry) => entry.key.length)
  );
  const barChart = [];
  if (!metrics.hasNegative) {
    for (const { key, value } of data) {
      const barLength = Math.floor(
        value / metrics.maxValue * chartLength
      );
      const bars = fillChar.repeat(barLength) + emptyChar.repeat(chartLength - barLength);
      let value_padded = " " + value.toString();
      if (rightAlignLabelsFlag === true) {
        value_padded = value_padded.padStart(maxValueLength + 1);
      }
      if (showLabelsFlag === true) {
        barChart.push(
          `${key.padEnd(
            maxKeyLength + 2
          )} ${prefixChar}${bars}${suffixChar}${value_padded}`
        );
      } else {
        barChart.push(
          `${key.padEnd(
            maxKeyLength + 2
          )} ${prefixChar}${bars}${suffixChar}`
        );
      }
    }
  } else {
    for (const { key, value } of data) {
      const bars = generateBidirectionalBar(
        value,
        metrics,
        chartLength,
        fillChar,
        emptyChar,
        zeroPointChar,
        showZeroPoint
      );
      let value_padded = " " + value.toString();
      if (rightAlignLabelsFlag === true) {
        value_padded = value_padded.padStart(maxValueLength + 1);
      }
      if (showLabelsFlag === true) {
        barChart.push(
          `${key.padEnd(
            maxKeyLength + 2
          )} ${prefixChar}${bars}${suffixChar}${value_padded}`
        );
      } else {
        barChart.push(
          `${key.padEnd(
            maxKeyLength + 2
          )} ${prefixChar}${bars}${suffixChar}`
        );
      }
    }
  }
  return barChart.join("\n");
}

// src/main.ts
var TinyChartPlugin = class extends import_obsidian2.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new SettingTab(this.app, this));
    this.addCommand({
      id: "horizontal-bar-example",
      name: "Insert horizontal barchart example",
      editorCallback: (editor, view) => {
        console.log(editor.getSelection());
        editor.replaceSelection(
          "```tinychart\nApples, 100\nBananas, 75\nOranges, 150\nGrapes, 25\nPineapples, 10\nWatermelons, 50\nstrawberries, 150\nBlueberries, 30\nRaspberries, 15\nMangoes, 150\n```"
        );
      }
    });
    this.addCommand({
      id: "horizontal-bar-bidirectional-example",
      name: "Insert bidirectional barchart example",
      editorCallback: (editor, view) => {
        editor.replaceSelection(
          "```tinychart\nRevenue, 150\nCosts, -120\nProfit, 80\nLoss, -40\nInvestment, 200\nDebt, -180\n```"
        );
      }
    });
    this.registerMarkdownCodeBlockProcessor(
      "tinychart",
      (source, el) => {
        try {
          const parsedData = parseInput(source);
          const barChart = generateBarChart(
            parsedData,
            this.settings
          );
          let codeBlockFlag = this.settings.codeBlock;
          let blockType;
          if (codeBlockFlag) {
            blockType = "pre";
          } else {
            blockType = "p";
          }
          const block = el.createEl(blockType, {
            attr: { style: "font-family: monospace;" }
          });
          block.innerText = barChart;
        } catch (error) {
          const errorEl = el.createEl("pre", {
            attr: { style: "color: red; font-family: monospace;" }
          });
          errorEl.innerText = "[TinyChart] \n" + error;
        }
      }
    );
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
